BTL_Nhom2/Areas/Admin/Controllers/AdminDanhMucsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BTL_Nhom2.Models;
using PagedList;

namespace BTL_Nhom2.Areas.Admin.Controllers
{
    public class AdminDanhMucsController : Controller
    {
        private TinhDauDB db = new TinhDauDB();

        // GET: Admin/AdminDanhMucs
        public ActionResult Category(int? page)
        {
            var danhMucs = db.DanhMucs.Select(d => d);
            danhMucs = danhMucs.OrderBy(s => s.MaDM);
            int pageSize = 5;
            int pageNumber = (page ?? 1);
            return View(danhMucs.ToPagedList(pageNumber, pageSize));
        }

        // GET: Admin/AdminDanhMucs/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/AdminDanhMucs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaDM,TenDM")] DanhMuc danhMuc)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.DanhMucs.Add(danhMuc);
                    db.SaveChanges();
                }
                return RedirectToAction("Category");
            }
            catch (Exception ex)
            {
                ViewBag.Error = "Lỗi nhập dữ liệu! " + ex.Message;
                return View(danhMuc);
            }
        }

        // GET: Admin/AdminDanhMucs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DanhMuc danhMuc = db.DanhMucs.Find(id);
            if (danhMuc == null)
            {
                return HttpNotFound();
            }
            return View(danhMuc);
        }

        // POST: Admin/AdminDanhMucs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaDM,TenDM")] DanhMuc danhMuc)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.Entry(danhMuc).State = EntityState.Modified;
                    db.SaveChanges();
                }
                return RedirectToAction("Category");
            }
            catch (Exception ex)
            {
                ViewBag.Error = "Lỗi nhập dữ liệu! " + ex.Message;
                return View(danhMuc);
            }
        }

        // GET: Admin/AdminDanhMucs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DanhMuc danhMuc = db.DanhMucs.Find(id);
            if (danhMuc == null)
            {
                return HttpNotFound();
            }
            return View(danhMuc);
        }

        // POST: Admin/AdminDanhMucs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            DanhMuc danhMuc = db.DanhMucs.Find(id);
            try
            {
                db.DanhMucs.Remove(danhMuc);
                db.SaveChanges();
                return RedirectToAction("Category");
            }
            catch (Exception ex)
            {
                ViewBag.Error = "Đã xảy ra lỗi! " + ex.Message;
                return View(danhMuc);
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BTL_Nhom2/Areas/Admin/Views/AdminDanhMucs/Category.cshtml
@model PagedList.IPagedList<BTL_Nhom2.Models.DanhMuc>
@using PagedList.Mvc;
@{
    ViewBag.Title = "Category";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

@section Title{
    Danh mục
}
<link href="~/Content/PagedList.css" rel="stylesheet" />
<style>
    .normal-text {
        text-transform: none;
    }

    .pagination {
        margin: 0px 0px;
    }
</style>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-6">
            <a href="@Url.Action("Create", "AdminDanhMucs")" class="btn btn-primary btn-sm normal-text" role="button">Thêm mới</a>
        </div>
        <div class="col-sm-6" style="text-align:right">
            @Html.PagedListPager(Model, page => Url.Action("Category", new { page }))
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header card-header-primary">
                    <h4 class="card-title">Danh sách các danh mục</h4>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-hover">
                            <thead class="text-primary">
                            <th>Mã danh mục</th>
                            <th>Tên danh mục</th>
                            <th>Hành động</th>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>@Html.DisplayFor(modelItem => item.MaDM)</td>
                                        <td>@Html.DisplayFor(modelItem => item.TenDM)</td>
                                        <td>
                                            @Html.ActionLink("Sửa", "Edit", new { id = item.MaDM }, new { @class = "btn btn-sm btn-primary normal-text" })
                                            @Html.ActionLink("Xóa", "Delete", new { id = item.MaDM }, new { @class = "btn btn-sm btn-primary normal-text" })
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div style="text-align: right">
        @Html.PagedListPager(Model, page => Url.Action("Category", new { page }))
    </div>
</div>

BTL_Nhom2/Areas/Admin/Views/AdminDanhMucs/Create.cshtml
@model BTL_Nhom2.Models.DanhMuc

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>DanhMuc</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.TenDM, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenDM, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenDM, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" style="background-color: purple;" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

BTL_Nhom2/Areas/Admin/Views/AdminDanhMucs/Delete.cshtml
@model BTL_Nhom2.Models.DanhMuc

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

@section Title{
    Xóa danh mục
}
<style>
    .dl-horizontal {
        padding-left: 10rem;
    }

    dl dd {
        padding-left: 8rem;
    }
</style>
<h3>Bạn có chắc muốn xóa danh mục này?</h3>
<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TenDM)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenDM)
        </dd>
        <dt>
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                <input type="submit" value="Xóa" class="btn btn-sm btn-primary normal-text" />
                @Html.ActionLink("Quay lại", "Category", null, new { @class = "btn btn-sm btn-primary normal-text" })
            }
        </dt>
    </dl>
</div>
@if (ViewBag.Error != null)
{
    <br />
    <div class="alert alert-danger" role="alert">@ViewBag.Error</div>
}

BTL_Nhom2/Areas/Admin/Views/AdminDanhMucs/Edit.cshtml
@model BTL_Nhom2.Models.DanhMuc

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

@section Title{
    Sửa danh mục
}
<style>
    .form-horizontal {
        padding-left: 7rem;
    }

    .col-md-10 {
        padding-left: 8rem;
    }

    .control-label, .bmd-form-group label {
        color: black;
    }
</style>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MaDM)

        <div class="form-group">
            @Html.LabelFor(model => model.TenDM, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenDM, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenDM, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Lưu" class="btn btn-sm btn-primary normal-text" />
                @Html.ActionLink("Quay lại", "Category", null, new { @class = "btn btn-sm btn-primary normal-text" })
            </div>
        </div>
    </div>
}
@if (ViewBag.Error != null)
{
    <br />
    <div class="alert alert-danger" role="alert">@ViewBag.Error</div>
}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}