BTL_Nhom2/Areas/Admin/Controllers/AdminSanPhamsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

using BTL_Nhom2.Models;
using PagedList;

namespace BTL_Nhom2.Areas.Admin.Controllers
{
    public class AdminSanPhamsController : Controller
    {
        private TinhDauDB db = new TinhDauDB();

        public ActionResult Product(int? page)
        {
            var sanPhams = db.SanPhams.Include(s => s.DanhMuc);
            sanPhams = sanPhams.OrderBy(s => s.MaSP);
            int pageSize = 5;
            int pageNumber = (page ?? 1);
            return View(sanPhams.ToPagedList(pageNumber, pageSize));
        }
        // GET: Admin/AdminSanPhams/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SanPham sanPham = db.SanPhams.Find(id);
            if (sanPham == null)
            {
                return HttpNotFound();
            }
            return View(sanPham);
        }

        // GET: Admin/AdminSanPhams/Create
        public ActionResult Create()
        {
            ViewBag.MaDM = new SelectList(db.DanhMucs, "MaDM", "TenDM");
            return View();
        }

        // POST: Admin/AdminSanPhams/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaSP,MaDM,TenSP,NhaSX,TrongLuong,SoLuongTon,Gia,ChatLuong,MoTa,Anh")] SanPham sanPham)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    sanPham.Anh = "";
                    var f = Request.Files["ImageFile"];
                    if (f != null && f.ContentLength > 0)
                    {
                        string FileName = System.IO.Path.GetFileName(f.FileName);
                        string UploadPath = Server.MapPath("~/wwwroot/image/" + FileName);
                        f.SaveAs(UploadPath);
                        sanPham.Anh = FileName;
                    }
                    if (db.SanPhams.Where(s => s.TenSP.ToLower().Equals(sanPham.TenSP.ToLower())).ToList().Count == 0)
                    {
                        db.SanPhams.Add(sanPham);
                        db.SaveChanges();
                    }
                    else
                    {
                        ViewBag.Error = "Tên sản phẩm đã tồn tại";
                        ViewBag.MaDM = new SelectList(db.DanhMucs, "MaDM", "TenDM", sanPham.MaDM);
                        return View(sanPham);
                    }
                }
                return RedirectToAction("Product");
            }
            catch (Exception ex)
            {
                ViewBag.Error = "Lỗi nhập dữ liệu! " + ex.Message;
                ViewBag.MaDM = new SelectList(db.DanhMucs, "MaDM", "TenDM", sanPham.MaDM);
                return View(sanPham);
            }
        }

        // GET: Admin/AdminSanPhams/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SanPham sanPham = db.SanPhams.Find(id);
            if (sanPham == null)
            {
                return HttpNotFound();
            }
            ViewBag.MaDM = new SelectList(db.DanhMucs, "MaDM", "TenDM", sanPham.MaDM);
            return View(sanPham);
        }

        // POST: Admin/AdminSanPhams/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaSP,MaDM,TenSP,NhaSX,TrongLuong,SoLuongTon,Gia,ChatLuong,MoTa,Anh")] SanPham sanPham)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var f = Request.Files["ImageFile"];
                    if (f != null && f.ContentLength > 0)
                    {
                        string FileName = System.IO.Path.GetFileName(f.FileName);
                        string UploadPath = Server.MapPath("~/wwwroot/image/" + FileName);
                        f.SaveAs(UploadPath);
                        sanPham.Anh = FileName;
                    }
                    /*else
                    {
                        string UploadPath = Server.MapPath("~/wwwroot/image/" + sanPham.Anh);
                    }*/
                    db.Entry(sanPham).State = EntityState.Modified;
                    db.SaveChanges();
                }
                return RedirectToAction("Product");
            }
            catch (Exception ex)
            {
                ViewBag.Error = "Lỗi nhập dữ liệu! " + ex.Message;
                ViewBag.MaDM = new SelectList(db.DanhMucs, "MaDM", "TenDM", sanPham.MaDM);
                return View(sanPham);
            }
            /*ViewBag.MaDM = new SelectList(db.DanhMucs, "MaDM", "TenDM", sanPham.MaDM);
            return View(sanPham);*/
        }

        // GET: Admin/AdminSanPhams/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SanPham sanPham = db.SanPhams.Find(id);
            if (sanPham == null)
            {
                return HttpNotFound();
            }
            return View(sanPham);
        }

        // POST: Admin/AdminSanPhams/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            SanPham sanPham = db.SanPhams.Find(id);

            try
            {
                db.SanPhams.Remove(sanPham);
                db.SaveChanges();
                return RedirectToAction("Product");
            }
            catch (Exception ex)
            {
                ViewBag.Error = "Không thể xóa sản phẩm này, Mã lỗi: " + ex.Message;
                return View(sanPham);
            }

        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BTL_Nhom2/Areas/Admin/Views/AdminSanPhams/Create.cshtml
@model BTL_Nhom2.Models.SanPham

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

@section Title{
    Thêm sản phẩm mới
}
@using (Html.BeginForm("Create", "AdminSanPhams", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header card-header-primary">
                        <h4 class="card-title">Thêm sản phẩm mới</h4>
                    </div>
                    <div class="card-body">
                        <form>
                            <div class="row">
                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                <div class="col-md-8">
                                    <div class="row">
                                        <div class="col-md-4">
                                            <div class="form-group">
                                                @Html.LabelFor(model => model.MaDM, "Tên danh mục", htmlAttributes: new { @class = "bmd-label-floating" })
                                                @Html.DropDownList("MaDM", null, htmlAttributes: new { @class = "form-control" })
                                                @Html.ValidationMessageFor(model => model.MaDM, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                        <div class="col-md-8">
                                            <div class="form-group">
                                                @Html.LabelFor(model => model.TenSP, htmlAttributes: new { @class = "bmd-label-floating" })
                                                @Html.EditorFor(model => model.TenSP, new { htmlAttributes = new { @class = "form-control", @style = "margin-top:2.6rem" } })
                                                @Html.ValidationMessageFor(model => model.TenSP, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-8">
                                            <div class="form-group">
                                                @Html.LabelFor(model => model.NhaSX, htmlAttributes: new { @class = "bmd-label-floating" })
                                                @Html.EditorFor(model => model.NhaSX, new { htmlAttributes = new { @class = "form-control" } })
                                                @Html.ValidationMessageFor(model => model.NhaSX, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                        <div class="col-md-4">
                                            <div class="form-group">
                                                @Html.LabelFor(model => model.TrongLuong, htmlAttributes: new { @class = "bmd-label-floating" })
                                                @Html.EditorFor(model => model.TrongLuong, new { htmlAttributes = new { @class = "form-control" } })
                                                @Html.ValidationMessageFor(model => model.TrongLuong, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-4">
                                            <div class="form-group">
                                                @Html.LabelFor(model => model.SoLuongTon, htmlAttributes: new { @class = "bmd-label-floating" })
                                                @Html.EditorFor(model => model.SoLuongTon, new { htmlAttributes = new { @class = "form-control" } })
                                                @Html.ValidationMessageFor(model => model.SoLuongTon, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                        <div class="col-md-4">
                                            <div class="form-group">
                                                @Html.LabelFor(model => model.Gia, htmlAttributes: new { @class = "bmd-label-floating" })
                                                @Html.EditorFor(model => model.Gia, new { htmlAttributes = new { @class = "form-control" } })
                                                @Html.ValidationMessageFor(model => model.Gia, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                        <div class="col-md-4">
                                            <div class="form-group">
                                                @Html.LabelFor(model => model.ChatLuong, htmlAttributes: new { @class = "bmd-label-floating" })
                                                @Html.EditorFor(model => model.ChatLuong, new { htmlAttributes = new { @class = "form-control" } })
                                                @Html.ValidationMessageFor(model => model.ChatLuong, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-12">
                                            <div class="form-group">
                                                @Html.LabelFor(model => model.MoTa, htmlAttributes: new { @class = "bmd-label-floating" })
                                                @Html.EditorFor(model => model.MoTa, new { htmlAttributes = new { @class = "form-control", rows = 3 } })
                                                @Html.ValidationMessageFor(model => model.MoTa, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="col-md-12">
                                        @Html.LabelFor(model => model.Anh, htmlAttributes: new { @class = "bmd-label-floating" })
                                        <br />
                                        <img id="output" class="img-rounded" alt="Ảnh" width="250" height="250"
                                             src="~/wwwroot/image/image_not_found.png" />
                                        <br />
                                        <label for="ufile" style="cursor: pointer; text-transform: none;" class="btn btn-sm btn-primary">Chọn tệp</label>
                                        <input name="ImageFile" id="ufile" type="file" style="display: none;"
                                               onchange="loadFile(event)" />
                                    </div>
                                </div>
                            </div>
                            <input type="submit" value="Thêm" class="btn btn-sm btn-primary normal-text" />
                            @Html.ActionLink("Quay lại", "Product", null, new { @class = "btn btn-sm btn-primary normal-text" })
                            <div class="clearfix"></div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
}
@if (ViewBag.Error != null)
{
    <br />
    <div class="alert alert-danger" role="alert">@ViewBag.Error</div>
}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}
<script>
    var loadFile = function (event) {
        var image = document.getElementById("output");
        image.src = URL.createObjectURL(event.target.files[0]);
    };
</script>

BTL_Nhom2/Areas/Admin/Views/AdminSanPhams/Edit.cshtml
@model BTL_Nhom2.Models.SanPham

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
    var ImagePath = "~/wwwroot/image/" + Model.Anh;
}
@section Title{
    Chỉnh sửa sản phẩm
}
@using (Html.BeginForm("Edit", "AdminSanPhams", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header card-header-primary">
                        <h4 class="card-title">Sửa thông tin sản phẩm</h4>
                    </div>
                    <div class="card-body">
                        <form>
                            <div class="row">
                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                <div class="col-md-8">
                                    @Html.HiddenFor(model => model.MaSP)
                                    <div class="row">
                                        <div class="col-md-4">
                                            <div class="form-group">
                                                @Html.LabelFor(model => model.MaDM, "Tên danh mục", htmlAttributes: new { @class = "bmd-label-floating" })
                                                @Html.DropDownList("MaDM", null, htmlAttributes: new { @class = "form-control" })
                                                @Html.ValidationMessageFor(model => model.MaDM, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                        <div class="col-md-8">
                                            <div class="form-group">
                                                @Html.LabelFor(model => model.TenSP, htmlAttributes: new { @class = "bmd-label-floating" })
                                                @Html.EditorFor(model => model.TenSP, new { htmlAttributes = new { @class = "form-control", @style = "margin-top:2.6rem" } })
                                                @Html.ValidationMessageFor(model => model.TenSP, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-8">
                                            <div class="form-group">
                                                @Html.LabelFor(model => model.NhaSX, htmlAttributes: new { @class = "bmd-label-floating" })
                                                @Html.EditorFor(model => model.NhaSX, new { htmlAttributes = new { @class = "form-control" } })
                                                @Html.ValidationMessageFor(model => model.NhaSX, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                        <div class="col-md-4">
                                            <div class="form-group">
                                                @Html.LabelFor(model => model.TrongLuong, htmlAttributes: new { @class = "bmd-label-floating" })
                                                @Html.EditorFor(model => model.TrongLuong, new { htmlAttributes = new { @class = "form-control" } })
                                                @Html.ValidationMessageFor(model => model.TrongLuong, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-4">
                                            <div class="form-group">
                                                @Html.LabelFor(model => model.SoLuongTon, htmlAttributes: new { @class = "bmd-label-floating" })
                                                @Html.EditorFor(model => model.SoLuongTon, new { htmlAttributes = new { @class = "form-control" } })
                                                @Html.ValidationMessageFor(model => model.SoLuongTon, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                        <div class="col-md-4">
                                            <div class="form-group">
                                                @Html.LabelFor(model => model.Gia, htmlAttributes: new { @class = "bmd-label-floating" })
                                                @Html.EditorFor(model => model.Gia, new { htmlAttributes = new { @class = "form-control" } })
                                                @Html.ValidationMessageFor(model => model.Gia, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                        <div class="col-md-4">
                                            <div class="form-group">
                                                @Html.LabelFor(model => model.ChatLuong, htmlAttributes: new { @class = "bmd-label-floating" })
                                                @Html.EditorFor(model => model.ChatLuong, new { htmlAttributes = new { @class = "form-control" } })
                                                @Html.ValidationMessageFor(model => model.ChatLuong, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-12">
                                            <div class="form-group">
                                                @Html.LabelFor(model => model.MoTa, htmlAttributes: new { @class = "bmd-label-floating" })
                                                @Html.EditorFor(model => model.MoTa, new { htmlAttributes = new { @class = "form-control", rows = 3 } })
                                                @Html.ValidationMessageFor(model => model.MoTa, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="col-md-12">
                                        @Html.LabelFor(model => model.Anh, htmlAttributes: new { @class = "bmd-label-floating" })
                                        <br />
                                        <img id="output" class="img-rounded" alt="Ảnh" width="250" height="250"
                                             src="@Url.Content(ImagePath)" />
                                        <br />
                                        <label for="ufile" style="cursor: pointer; text-transform: none;" class="btn btn-sm btn-primary">Chọn tệp</label>
                                        <input name="ImageFile" id="ufile" type="file" style="display: none;"
                                               onchange="loadFile(event)" />
                                        @Html.HiddenFor(model => model.Anh)
                                    </div>
                                </div>
                            </div>
                            <input type="submit" value="Lưu" class="btn btn-sm btn-primary normal-text" />
                            @Html.ActionLink("Quay lại", "Product", null, new { @class = "btn btn-sm btn-primary normal-text" })
                            <div class="clearfix"></div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
}
@if (ViewBag.Error != null)
{
    <br />
    <div class="alert alert-danger" role="alert">@ViewBag.Error</div>
}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}
<script>
    var loadFile = function (event) {
        var image = document.getElementById("output");
        image.src = URL.createObjectURL(event.target.files[0]);
    };
</script>

BTL_Nhom2/Areas/Admin/Views/AdminSanPhams/Product.cshtml
@model PagedList.IPagedList<BTL_Nhom2.Models.SanPham>
@using PagedList.Mvc;
@{
    ViewBag.Title = "Product";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

@section Title{
    Sản phẩm
}
<link href="~/Content/PagedList.css" rel="stylesheet" />
<style>
    .normal-text {
        text-transform: none;
    }
    .pagination {
        margin: 0px 0px;
    }
</style>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-6">
            <a href="@Url.Action("Create", "AdminSanPhams")" class="btn btn-primary btn-sm normal-text" role="button">Thêm mới</a>
        </div>
        <div class="col-sm-6" style="text-align:right">
            @Html.PagedListPager(Model, page => Url.Action("Product", new { page }))
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header card-header-primary">
                    <h4 class="card-title">Danh sách sản phẩm</h4>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-hover">
                            <thead class="text-primary">
                            <th>Hình ảnh</th>
                            <th>Tên sản phẩm</th>
                            <th>Nhà sản xuất</th>
                            <th>Số lượng tồn</th>
                            <th>Giá bán</th>
                            <th>Hành động</th>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>
                                            @{
                                                string imagePath = "~/wwwroot/image/" + item.Anh;
                                            }
                                            <img src="@Url.Content(imagePath)" width="70" class="img-thumbnail" />
                                            <br />
                                            @Html.HiddenFor(modelItem => item.Anh)
                                        </td>
                                        <td>@Html.DisplayFor(modelItem => item.TenSP)</td>
                                        <td>@Html.DisplayFor(modelItem => item.NhaSX)</td>
                                        <td>@Html.DisplayFor(modelItem => item.SoLuongTon)</td>
                                        <td>@Html.DisplayFor(modelItem => item.Gia) VND</td>
                                        <td>
                                            @Html.ActionLink("Chi tiết", "Details", new { id = item.MaSP }, new { @class = "btn btn-sm btn-primary normal-text" })
                                            @Html.ActionLink("Sửa", "Edit", new { id = item.MaSP }, new { @class = "btn btn-sm btn-primary normal-text" })
                                            @Html.ActionLink("Xóa", "Delete", new { id = item.MaSP }, new { @class = "btn btn-sm btn-primary normal-text" })
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div style="text-align: right">
        @Html.PagedListPager(Model, page => Url.Action("Product", new { page }))
    </div>
</div>